### PR TITLE
update Erlang version to 24.0.2

### PR DESCRIPTION
**Pull request by maco**
Thanks to @HangingClowns for figuring out the depencies in #102. @tomciopp asked for a rebase on top of master, and that's what this is for.

### CODE REVIEW

**Comment by tomciopp** [comment]
@maco @bitwalker To my knowledge it shouldn't be necessary to include C++ when building erlang. Could you provide a bit more context as to why this is included in this PR? I'm guessing this fixes some problem that you're having but I would rather see what the true issue is before adding unnecessary dependencies to the Dockerfile. (We want to avoid treating symptoms rather than the disease) If you could include any error messages that you were seeing that would be helpful.

**Comment by HangingClowns** [comment]
Hi, I believe this is required for the JIT to function properly. I tried to use elixir and elixir wouldn’t work so I went back and added these c++ deps and everything seems to be functioning.

**Review by bitwalker — APPROVED** [review]

**Comment by bitwalker** [comment]
This is probably due to AsmJIT being part of the distribution now

**Comment by tomciopp** [comment]
@bitwalker Taken from https://erlang.org/download/OTP-24.0.README

```
OTP-16885    Application(s): erts
               Related Id(s): PR-2745

               The BeamAsm JIT-compiler has been added to Erlang/OTP.
               The JIT-compiler is enabled by default on most x86
               64-bit platforms that have a C++ compiler that can
               compile C++17. To verify that a JIT enabled emulator is
               running you can use erlang:system_info(emu_flavor).

               For more information see the internal documentation of
               BeamAsm in erts.
```

What is confusing to me, is the fact that `gcc` should include this library by default. So why wasn't this working out of the box? 

https://gcc.gnu.org/

```
The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, and D, as well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.
```

**Comment by tomciopp** [comment]
Ah ok, we didn't have `gcc` installed apparently. @HangingClowns @maco have you tried running this without `libstdc++`? I think it may be redundant after adding `libgcc`

**Comment by bitwalker** [comment]
Yeah I wouldn't expect `libstdc++` to be necessary, at least explicitly.

**Comment by maco** [comment]
I haven't tried them separate. @HangingClowns ?

**Comment by HangingClowns** [comment]
I have not, but what I did see is some errors saying i needed some libs: so i googled for them, I saw each package was listed separately.

**Comment by bitwalker** [comment]
I'm testing the build without libstdc++ myself, I'll merge the changes if it checks out

**Pull request merged**
