### PR TITLE
Update to alpine 3.19.0 and erlang 26.2.1

### PR DESCRIPTION
**Pull request by drmartinberger**

### CODE REVIEW

**Review by bitwalker — APPROVED** [review]

**Comment by drmartinberger** [comment]
Hi @bitwalker,

can you re-run the lastest master build again to check if problems persist?

Build on fork worked fine: https://github.com/bitwalker/alpine-erlang/pull/134/checks
Build on master failed: https://github.com/bitwalker/alpine-erlang/actions/runs/7591179754/job/20678881407

Thank you!

BR, Martin

**Comment by drmartinberger** [comment]
Hey @bitwalker, did you find time to look into it? Thank you! BR, Martin

**Comment by drmartinberger** [comment]
Hi @bitwalker,

can you please re-run last build for master?
https://github.com/bitwalker/alpine-erlang/actions/runs/7591179754/job/20678881407

Thank you!

BR, Martin

**Comment by drmartinberger** [comment]
See #135, should resolve the issues described above.

**Pull request merged**
