### PR TITLE
chore(ERLANG_VERSION): Update to 23.2.3

### PR DESCRIPTION
**Pull request by tomciopp**
@bitwalker Another patch of erlang has been released

https://erlang.org/download/OTP-23.2.3.README

### CODE REVIEW

**Comment by tomciopp** [comment]
Hmm looks like the build failed. I'm unfamiliar with `buildx`, but should we run `make setup-buildx && make build` instead of just `make build`?

**Comment by bitwalker** [comment]
Yeah I think that's what it's complaining about. I thought the action I'm using set up the builder, but I guess not. If you don't get to it before I'm at my computer again, I'll try it out, or I'll manually push it

**Comment by tomciopp** [comment]
Hmm getting a new error 

```
failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c apk add --no-cache --update pcre@edge &&     apk add --no-cache --update       bash       ca-certificates       openssl-dev       ncurses-dev       unixodbc-dev       zlib-dev]: exit code: 1
```

**Comment by tomciopp** [comment]
@bitwalker Not quite sure why `buildx` is failing. Looks like it is having an issue with making a call to `apk`? Any thoughts?

**Comment by tomciopp** [comment]
Also is there still a reason why we need to use `pcre@edge` instead of just `pcre`?

**Review by bitwalker — APPROVED** [review]

**Pull request merged**
