### PR TITLE
chore(Erlang + Alpine): Update erlang to 23.2 and alpine to 3.12.3

### PR DESCRIPTION
**Pull request by tomciopp**
@bitwalker They released another new version of alpine linux and erlang.

Highlights from alpine include security fixes for openssl, imagemagick, and linux-lts to 5.4.83. 

https://alpinelinux.org/posts/Alpine-3.12.3-released.html
https://alpinelinux.org/posts/Alpine-3.12.2-released.html

https://erlang.org/download/OTP-23.2.README

### CODE REVIEW

**Comment by tomciopp** [comment]
@bitwalker Is everything ok? It usually doesn't take this long to get these PRs merged.

**Comment by bitwalker** [comment]
@tomciopp So sorry man, I've been absolutely swamped with work as of late, I'll try and set up some additional automation to make it so I'm not as much of a blocker.

**Comment by bitwalker** [comment]
@tomciopp If you are open to it, I'm happy to make you a comitter on this repo, and provide access to push images.

**Comment by tomciopp** [comment]
@bitwalker I'd be cool with that.

**Comment by bitwalker** [comment]
@tomciopp I've added you as a committer on the repo. Yesterday I set up automation to build the image on pushes/PRs, and publish the image automatically when pushes to master occur. For now, things are set up to require a PR for anything to be merged to master, with a review from whichever of us is not the author of the PR. Since I only need to sign off on a PR, I should be able to keep up with the changes with no delay - but if I end up delaying things again, we can change it so that you can merge without a review. I'm quite sensitive to giving unfettered access to tools that let people publish things under my name, so I hope you'll entertain my foibles in that regard 😛

**Comment by tomciopp** [comment]
@bitwalker That's completely understandable, and I would do the same if it we were to change places.

**Pull request merged**
